# Generated by Django 6.0.3 on 2026-03-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='coordinates',
            field=models.JSONField(blank=True, help_text='GeoJSON coordinates of the polygon', null=True),
        ),
    ]
