# Generated by Django 6.0.3 on 2026-03-19 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_data', '0002_district_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='map_data.district'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crimes', to='map_data.district'),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_stations', to='map_data.district'),
        ),
        migrations.AlterField(
            model_name='socialobject',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_objects', to='map_data.district'),
        ),
    ]
